# Generated by Django 5.2.9 on 2026-01-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_activities",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total activities"
                    ),
                ),
                (
                    "logins",
                    models.PositiveIntegerField(default=0, verbose_name="logins"),
                ),
                (
                    "posts_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="posts created"
                    ),
                ),
                (
                    "comments_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="comments created"
                    ),
                ),
                (
                    "likes_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="likes received"
                    ),
                ),
                (
                    "followers_gained",
                    models.PositiveIntegerField(
                        default=0, verbose_name="followers gained"
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="longest streak"
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="last active"),
                ),
                (
                    "show_activity",
                    models.BooleanField(default=True, verbose_name="show activity"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user activity aggregation",
                "verbose_name_plural": "user activity aggregations",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privacy_setting",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Who can see your profile and activity",
                        max_length=10,
                        verbose_name="privacy setting",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for activity",
                        verbose_name="email notifications",
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive push notifications for activity",
                        verbose_name="push notifications",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="website"),
                ),
                (
                    "github_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="GitHub username",
                    ),
                ),
                (
                    "twitter_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Twitter username",
                    ),
                ),
                (
                    "linkedin_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="LinkedIn username",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="location"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="occupation"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="company"
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System Default"),
                        ],
                        default="system",
                        max_length=10,
                        verbose_name="theme preference",
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="language preference",
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="last active"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "profile_background",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_backgrounds/",
                        verbose_name="profile background",
                    ),
                ),
                (
                    "blocked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="blocked users",
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="following",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Registration"),
                            ("profile_update", "Profile Update"),
                            ("password_change", "Password Change"),
                            ("post_create", "Post Created"),
                            ("post_like", "Post Liked"),
                            ("comment_create", "Comment Created"),
                            ("comment_like", "Comment Liked"),
                            ("follow", "Followed User"),
                            ("unfollow", "Unfollowed User"),
                            ("block", "Blocked User"),
                            ("unblock", "Unblocked User"),
                        ],
                        max_length=50,
                        verbose_name="activity type",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_usera_user_id_250303_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="users_usera_activit_257cae_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="users_usera_created_222448_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="session key"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="last activity"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user session",
                "verbose_name_plural": "user sessions",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="users_users_user_id_f9f20a_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-last_activity"],
                        name="users_users_is_acti_493f02_idx",
                    ),
                ],
            },
        ),
    ]
